services:
  postgres:
    image: postgres:17.0
    container_name: outbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: outbox
      POSTGRES_PASSWORD: outbox
      POSTGRES_DBNAME: outbox
    ports:
      - 5130:5432
